version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: whatson
      POSTGRES_PASSWORD: whatson_dev
      POSTGRES_DB: whatson
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
