const { query } = require('../db/pool')
const T = (slug,title,description,stops,opts={}) => ({ slug,title,description,stops,duration:opts.duration||240,time:opts.time||['afternoon','evening'],weather:opts.weather||['mixed'],budget:opts.budget||['cheap','moderate','premium'],audience:opts.audience||['solo','couple','friends','family'],energy:opts.energy||'balanced',walking:opts.walking||'moderate',metadata:opts.metadata||{} })
const S = (role,categories,extra={}) => ({ role,categories,required:extra.required!==false,swappable:extra.swappable!==false,minRating:extra.minRating||4, budget:extra.budget||[], ambience:extra.ambience||[], walk:extra.walk||1200,duration:extra.duration||60 })
const templates = [
 T('classic-day-out','Classic Day Out','A balanced introduction to a city.',[S('Coffee',['cafe']),S('Explore',['park','attraction','museum']),S('Lunch',['restaurant','market']),S('Drinks',['bar','pub'])]),
 T('hidden-gems','Hidden Gems','Independent places and local favourites.',[S('Coffee',['cafe']),S('Discover',['gallery','market','attraction']),S('Local lunch',['restaurant']),S('Local drinks',['bar','pub'])],{metadata:{keywords:['hidden','local','discover']}}),
 T('date-night','Date Night','An easy, memorable evening for two.',[S('Aperitif',['bar','pub']),S('Dinner',['restaurant'],{minRating:4.2}),S('After dinner',['bar','music_venue'])],{time:['evening'],audience:['couple'],energy:'relaxed'}),
 T('rainy-escape','Rainy Escape','A cosy all-weather escape.',[S('Coffee',['cafe']),S('Culture',['museum','gallery']),S('Lunch',['restaurant']),S('Cosy drinks',['pub','bar'])],{weather:['indoor','rain'],walking:'low'}),
 T('foodie-adventure','Foodie Adventure','A city explored through brilliant food.',[S('Coffee',['cafe']),S('Small plates',['restaurant','market']),S('Dessert',['cafe','bakery']),S('Drinks',['bar','pub'])],{metadata:{keywords:['food','foodie','eat']}}),
 T('waterfront-wander','Waterfront Wander','Fresh air, views and a good table.',[S('Coffee',['cafe']),S('Waterfront walk',['park','attraction']),S('Lunch',['restaurant']),S('Sunset drinks',['bar','pub'])],{weather:['outdoor','mixed'],walking:'high'}),
 T('cultural-explorer','Cultural Explorer','Art, history and thoughtful pauses.',[S('Coffee',['cafe']),S('Museum',['museum','gallery']),S('Lunch',['restaurant']),S('Culture nightcap',['bar','pub'])]),
 T('family-adventure','Family Adventure','A relaxed day that works for all ages.',[S('Fuel up',['cafe']),S('Activity',['park','attraction','museum']),S('Family lunch',['restaurant']),S('Treat',['bakery','cafe'])],{audience:['family'],energy:'balanced'}),
 T('solo-reset','Solo Reset','A calm, restorative few hours.',[S('Coffee',['cafe']),S('Fresh air',['park','garden']),S('Quiet culture',['museum','gallery']),S('Slow bite',['cafe','restaurant'])],{audience:['solo'],energy:'low'}),
 T('sunday-slow','Sunday Slow','A gentle Sunday with no rushing.',[S('Brunch',['cafe','restaurant']),S('Wander',['park','market','gallery']),S('Sunday drink',['pub','bar'])],{time:['morning','afternoon'],energy:'low'}),
 T('live-music-night','Live Music Night','Dinner, then a night with a soundtrack.',[S('Dinner',['restaurant']),S('Pre-show drinks',['bar','pub']),S('Live music',['music_venue','bar'])],{time:['evening','late_night'],energy:'high'}),
 T('pub-trail','Pub Trail','A considered pub crawl with short hops.',[S('First pint',['pub']),S('Second pub',['pub']),S('Food stop',['restaurant','pub']),S('Final pub',['pub'])],{time:['afternoon','evening'],energy:'high',walking:'moderate'}),
 T('shopping-day','Shopping Day','Browse, refuel and recharge.',[S('Coffee',['cafe']),S('Browse',['market','attraction']),S('Lunch',['restaurant']),S('Treat',['bakery','cafe'])],{time:['morning','afternoon']}),
 T('active-explorer','Active Explorer','Move through the city and earn the treats.',[S('Coffee',['cafe']),S('Active stop',['park','attraction']),S('Lunch',['restaurant']),S('Recovery drink',['cafe','pub'])],{weather:['outdoor','mixed'],energy:'high',walking:'high'}),
 T('first-time-visitor','First Time Visitor','The city’s essential first impression.',[S('Orientation coffee',['cafe']),S('Landmark',['landmark','attraction','museum']),S('Local lunch',['restaurant']),S('View or drink',['bar','pub','attraction'])]),
 T('romantic-afternoon','Romantic Afternoon','A lovely daytime date.',[S('Coffee',['cafe']),S('Stroll',['park','gallery','attraction']),S('Lunch',['restaurant']),S('Cocktails',['bar'])],{time:['afternoon'],audience:['couple'],energy:'relaxed'}),
 T('student-budget-day','Student Budget Day','A good city day without stretching the budget.',[S('Cheap coffee',['cafe'],{budget:['cheap']}),S('Free explore',['park','museum','gallery']),S('Affordable food',['restaurant','market'],{budget:['cheap']}),S('Value drinks',['pub','bar'],{budget:['cheap']})],{budget:['cheap']}),
 T('creative-quarter','Creative Quarter','Independent art, food and atmosphere.',[S('Coffee',['cafe']),S('Creative stop',['gallery','market','attraction']),S('Independent lunch',['restaurant']),S('Atmosphere',['bar','pub'])]),
 T('sunset-experience','Sunset Experience','Time the best views with a brilliant finish.',[S('Early bite',['restaurant','cafe']),S('Golden hour',['park','attraction','landmark']),S('Sunset drinks',['bar','pub'])],{time:['afternoon','evening'],weather:['outdoor','mixed'],audience:['solo','couple','friends']}),
 T('night-owl','Night Owl','Late food, late drinks and places that stay open.',[S('Late food',['restaurant']),S('Drinks',['bar','pub']),S('Late night',['nightclub','music_venue','bar'])],{time:['late_night','evening'],energy:'high'}),
]
async function seedExperienceTemplates() {
 for (const t of templates) {
  const { rows:[row] } = await query(`INSERT INTO experience_templates (slug,title,description,duration_minutes,ideal_time,ideal_weather,budget,audience,energy_level,walking_preference,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,duration_minutes=EXCLUDED.duration_minutes,ideal_time=EXCLUDED.ideal_time,ideal_weather=EXCLUDED.ideal_weather,budget=EXCLUDED.budget,audience=EXCLUDED.audience,energy_level=EXCLUDED.energy_level,walking_preference=EXCLUDED.walking_preference,metadata=EXCLUDED.metadata,updated_at=now() RETURNING id`,[t.slug,t.title,t.description,t.duration,JSON.stringify(t.time),JSON.stringify(t.weather),JSON.stringify(t.budget),JSON.stringify(t.audience),t.energy,t.walking,JSON.stringify(t.metadata)])
  await query('DELETE FROM experience_template_stops WHERE template_id=$1',[row.id])
  for (const [i,s] of t.stops.entries()) await query(`INSERT INTO experience_template_stops (template_id,stop_order,role,venue_categories,required,swappable,minimum_rating,preferred_budget,preferred_ambience,preferred_walking_distance_m,duration_minutes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[row.id,i+1,s.role,JSON.stringify(s.categories),s.required,s.swappable,s.minRating,JSON.stringify(s.budget),JSON.stringify(s.ambience),s.walk,s.duration])
 }
 return templates.length
}
module.exports = { seedExperienceTemplates, templates }
